baseURL: https://blog.zoftko.com/
languageCode: en-us
title: ZoftKo
theme: PaperMod
menu:
  main:
      - name: Posts
        url: /posts/
      - name: Tags
        url: /tags/
      - name: Search
        url: /search/
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  env: production
  description: "Electronics and Software Development projects."
  author: Antonio
  showToc: true
  showCodeCopyButtons: true
  showPostNavLinks: true
  homeInfoParams:
    title: ZoftKo Blog
    content: This blog documents the development of electronics/software projects. Most of the
      source code involved in said projects can be found in the git providers linked below.
      Information provided here is by no means authoritative yet it may be of value to persons
      developing similar projects. If you see any mistakes/inaccuracies feel free to suggest changes.
  socialIcons:
    - name: github
      url: "https://github.com/zoftko"
    - name: gitlab
      url: "https://gitlab.com/zoftko"
  editPost:
    URL: "https://github.com/zoftko/blog/blob/main/content"
    text: "Suggest changes"
    appendFilePath: true
